add tm_mobilefacenet
OAID/Tengine pull request #384
Opened 2020-08-26 06:22 UTC by shitouren1994

增加tengine-lite mobilefacenet demo，自测使用的模型是model zoo百度网盘中others/Tengin_models/mobileface中的mobile_77 caffe模型，然后使用在线转换转成tmfile。
功能：输入模型，a的照片，b的照片，输出两者特征向量的余弦相似度。
问题：自测时发现相同人的照片余弦相似度大于0.9但是不同人照片相似度也达到了0.7多，可能与图片的预处理有关。

2020-08-26 15:48 UTC, BUG1989 reviewed
谢谢您的修复

2020-08-26 15:51 UTC, BUG1989 requested changes
tm_mobilefacenet.cpp ，如果方便的话，请使用根目录下的 clang-formate 文件进行格式 refactor，谢谢。

2020-08-27 02:38 UTC, BUG1989 approved these changes
谢谢您的贡献！

2020-08-27 02:38 UTC, merged

2022-10-12 02:27 UTC, wei8171023 commented
@shitouren1994 @BUG1989 您好，我用网页转换mobile_77 caffe模型到tmfile后，，推理最后的128维向量中有个别很多的数值，是为什么呢？谢谢！

2022-10-12 02:41 UTC, wei8171023 commented
@shitouren1994 @BUG1989 您好，请问我在网页上将others/Tengin_models/mobileface中的mobile_77 caffe模型转到tmfile文件，使用tm_mobilefacenet.cpp，结果的128维向量有有个别数很大，导致最终结果不正确。请问这个跟什么有关系呢？
![image](https://user-images.githubusercontent.com/43906624/195237022-a8b797bd-fd36-4c61-b385-4d7f0c2cfbdc.png)