optimize the impl of int8
OAID/Tengine pull request #531
Opened 2021-01-16 13:55 UTC by BUG1989

2021-01-16 14:46 UTC, kalcohol requested changes

2021-01-16 14:46 UTC, kalcohol commented on CMakeLists.txt
> +add_definitions(-O3)
why this has been modified?

2021-01-16 15:02 UTC, kalcohol approved these changes

2021-01-17 00:13 UTC, BUG1989 commented on CMakeLists.txt
> +add_definitions(-O3)
The default cfg of NDK is O2.

2021-01-17 01:55 UTC, merged