fix: fix tengine vs2019 build for lib and examples
OAID/Tengine pull request #927
Opened 2021-07-27 03:20 UTC by zchrissirhcz

环境 VS2019
修复 tengine lib 编译时，类型报错，  void* / float* / uint8_t* 显示转换
修复 很多 example 中的 std::max / std::min 编译报错

2021-07-27 03:22 UTC, kalcohol requested changes, later dismissed

2021-07-27 03:22 UTC, kalcohol commented on examples/CMakeLists.txt
> +set(OpenCV_DIR "E:/lib/opencv/4.5.2" CACHE PATH "")
remove this line

2021-07-27 03:38 UTC, zchrissirhcz commented on examples/CMakeLists.txt
> +set(OpenCV_DIR "E:/lib/opencv/4.5.2" CACHE PATH "")
OK, removed in next commit.

2021-07-27 03:38 UTC, zchrissirhcz commented
Also tested on local ubuntu 20.04 machine.
Examples built OK.

2021-07-27 12:24 UTC, BUG1989 approved these changes
lgtm!

2021-07-27 12:36 UTC, BUG1989 approved these changes
lgtm!

2021-07-27 12:38 UTC, BUG1989 commented on examples/CMakeLists.txt
> +set(OpenCV_DIR "E:/lib/opencv/4.5.2" CACHE PATH "")
done.

2021-07-27 12:51 UTC, cmdbug commented
zz yes!

2021-07-27 12:52 UTC, BUG1989 commented
@cmdbug Who are you ?

2021-07-27 13:01 UTC, merged

2021-07-28 00:07 UTC, cmdbug commented
> @cmdbug Who are you ?

小莫愁